default_platform(:ios)

platform :ios do
  desc "Build and upload to Firebase App Distribution (beta)"
  lane :beta do
  end
end

platform :android do
  desc "Build and upload to Firebase App Distribution (beta)"
  lane :beta do
  end
end
