import 'dart:io';
import 'dart:typed_data';

import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

import '../../core/health/dose_log.dart';
import '../../core/health/vitals_store.dart';
import '../../shared/models/models.dart';

const _gold = PdfColor.fromInt(0xFFC8A96E);
const _ink = PdfColor.fromInt(0xFF1A1C2E);

/// Builds a branded, clinician-ready PDF and opens the system share sheet.
Future<void> shareHealthReportPdf({
  required String recipient,
  required String coverNote,
  required String rangeLabel,
  required HealthOverview overview,
  required AdherenceData adherence,
  required VitalsLog vitals,
}) async {
  final bytes = await buildHealthReportPdf(
    recipient: recipient,
    coverNote: coverNote,
    rangeLabel: rangeLabel,
    overview: overview,
    adherence: adherence,
    vitals: vitals,
  );
  final dir = await getTemporaryDirectory();
  final file = File('${dir.path}/elinacura_health_report.pdf');
  await file.writeAsBytes(bytes);
  await Share.shareXFiles(
    [XFile(file.path, mimeType: 'application/pdf')],
    text: 'ElinaCura health report',
    subject: 'ElinaCura health report',
  );
}

Future<Uint8List> buildHealthReportPdf({
  required String recipient,
  required String coverNote,
  required String rangeLabel,
  required HealthOverview overview,
  required AdherenceData adherence,
  required VitalsLog vitals,
}) async {
  final doc = pw.Document();
  final profile = overview.profile;
  final now = DateTime.now();
  final dateStr = '${now.year}-${now.month.toString().padLeft(2, '0')}-'
      '${now.day.toString().padLeft(2, '0')}';

  doc.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.fromLTRB(36, 40, 36, 40),
      build: (context) => [
        _header(profile?.name ?? 'Patient', recipient, dateStr, rangeLabel),
        pw.SizedBox(height: 18),
        if (coverNote.trim().isNotEmpty) ...[
          _noteBox(coverNote.trim()),
          pw.SizedBox(height: 16),
        ],
        _adherenceBlock(adherence),
        pw.SizedBox(height: 18),
        _vitalsBlock(vitals),
        pw.SizedBox(height: 18),
        _medsBlock(overview.medications),
        pw.SizedBox(height: 18),
        _conditionsBlock(overview.conditions),
      ],
      footer: (context) => pw.Container(
        alignment: pw.Alignment.centerRight,
        margin: const pw.EdgeInsets.only(top: 8),
        child: pw.Text(
          'Generated by ElinaCura · Page ${context.pageNumber}/${context.pagesCount}',
          style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
        ),
      ),
    ),
  );
  return doc.save();
}

pw.Widget _header(String patient, String recipient, String date, String range) {
  return pw.Column(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('ElinaCura',
                  style: pw.TextStyle(
                      fontSize: 22,
                      fontWeight: pw.FontWeight.bold,
                      color: _gold)),
              pw.Text('Personal Health Report',
                  style: const pw.TextStyle(fontSize: 11, color: PdfColors.grey700)),
            ],
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text('Prepared for', style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
              pw.Text(recipient.isEmpty ? 'Clinician' : recipient,
                  style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
              pw.Text(date, style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
            ],
          ),
        ],
      ),
      pw.SizedBox(height: 10),
      pw.Container(height: 2, color: _gold),
      pw.SizedBox(height: 10),
      pw.Text('Patient: $patient   ·   Range: $range',
          style: pw.TextStyle(fontSize: 11, color: _ink)),
    ],
  );
}

pw.Widget _sectionTitle(String t) => pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 6),
      child: pw.Text(t.toUpperCase(),
          style: pw.TextStyle(
              fontSize: 10,
              fontWeight: pw.FontWeight.bold,
              color: _gold,
              letterSpacing: 1.0)),
    );

pw.Widget _noteBox(String note) => pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Text(note, style: const pw.TextStyle(fontSize: 11)),
    );

pw.Widget _adherenceBlock(AdherenceData a) {
  return pw.Column(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      _sectionTitle('Adherence'),
      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.end,
        children: [
          pw.Text('${a.hasSchedule ? a.todayPercent : 0}%',
              style: pw.TextStyle(
                  fontSize: 28, fontWeight: pw.FontWeight.bold, color: _gold)),
          pw.SizedBox(width: 12),
          pw.Padding(
            padding: const pw.EdgeInsets.only(bottom: 4),
            child: pw.Text(
              a.hasSchedule
                  ? '${a.todayTaken}/${a.todayScheduled} doses today'
                  : 'No active schedule',
              style: const pw.TextStyle(fontSize: 11, color: PdfColors.grey700),
            ),
          ),
        ],
      ),
      pw.SizedBox(height: 10),
      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.end,
        children: [
          for (final r in a.weekRatios)
            pw.Container(
              width: 22,
              height: 6 + 38 * r,
              margin: const pw.EdgeInsets.only(right: 6),
              decoration: pw.BoxDecoration(
                color: r > 0 ? _gold : PdfColors.grey300,
                borderRadius: pw.BorderRadius.circular(3),
              ),
            ),
        ],
      ),
      pw.SizedBox(height: 4),
      pw.Text('Trailing 7 days', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
    ],
  );
}

pw.Widget _vitalsBlock(VitalsLog vitals) {
  final rows = <pw.TableRow>[
    pw.TableRow(
      decoration: const pw.BoxDecoration(color: PdfColors.grey100),
      children: [
        _cell('Metric', bold: true),
        _cell('Latest', bold: true),
        _cell('Unit', bold: true),
        _cell('Status', bold: true),
      ],
    ),
  ];
  for (final type in VitalType.values) {
    final entries = vitals[type];
    if (entries == null || entries.isEmpty) continue;
    final v = entries.last.value;
    rows.add(pw.TableRow(children: [
      _cell(type.label),
      _cell(type == VitalType.weight ? v.toStringAsFixed(1) : v.toStringAsFixed(0)),
      _cell(type.unit),
      _cell(type.statusLabel(v) ?? '—'),
    ]));
  }
  return pw.Column(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      _sectionTitle('Vitals'),
      if (rows.length == 1)
        pw.Text('No vitals logged in this range.',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600))
      else
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
          columnWidths: const {
            0: pw.FlexColumnWidth(2),
            1: pw.FlexColumnWidth(1),
            2: pw.FlexColumnWidth(1),
            3: pw.FlexColumnWidth(1.4),
          },
          children: rows,
        ),
    ],
  );
}

pw.Widget _cell(String text, {bool bold = false}) => pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 5),
      child: pw.Text(text,
          style: pw.TextStyle(
              fontSize: 10,
              fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal)),
    );

pw.Widget _medsBlock(List<MedicationItem> meds) {
  return pw.Column(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      _sectionTitle('Medications'),
      if (meds.isEmpty)
        pw.Text('No medications on file.',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600))
      else
        ...meds.map(
          (m) => pw.Padding(
            padding: const pw.EdgeInsets.only(bottom: 4),
            child: pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Container(
                  width: 5,
                  height: 5,
                  margin: const pw.EdgeInsets.only(top: 4, right: 8),
                  decoration: const pw.BoxDecoration(
                      color: _gold, shape: pw.BoxShape.circle),
                ),
                pw.Expanded(
                  child: pw.Text(
                    '${m.name}'
                    '${m.dose.isNotEmpty ? ' · ${m.dose}' : ''}'
                    '${m.schedule.isNotEmpty ? ' · ${m.schedule}' : ''}',
                    style: const pw.TextStyle(fontSize: 11),
                  ),
                ),
              ],
            ),
          ),
        ),
    ],
  );
}

pw.Widget _conditionsBlock(List<ConditionItem> conditions) {
  return pw.Column(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      _sectionTitle('Conditions'),
      if (conditions.isEmpty)
        pw.Text('No conditions on file.',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600))
      else
        pw.Wrap(
          spacing: 6,
          runSpacing: 6,
          children: conditions
              .map((c) => pw.Container(
                    padding:
                        const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 5),
                    decoration: pw.BoxDecoration(
                      border: pw.Border.all(color: PdfColors.grey400, width: 0.5),
                      borderRadius: pw.BorderRadius.circular(20),
                    ),
                    child: pw.Text(
                      '${c.name}${c.status.isNotEmpty ? ' · ${c.status}' : ''}',
                      style: const pw.TextStyle(fontSize: 10),
                    ),
                  ))
              .toList(),
        ),
    ],
  );
}
